# -*- coding: utf-8 -*-
"""Listagem de melhores games.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYqeTYmSBCwYST_AAOCMRpfDDH71StE9
"""

!pip install -q -U google-generativeai

import google.generativeai as genai
from google.colab import userdata
api_key = userdata.get('SECRET_KEY')
genai.configure(api_key=api_key)

model = genai.GenerativeModel('gemini-pro')

response = model.generate_content("Crie uma tabela no formato JSON. Pense na história do mundo dos games. Faça a lista com as 10 maiores notas do metacritic em ordem. Use quatro variáveis: titulo_do_game, plataforma,data_de_lancamento e nota.")
print(response.text)